name: Add nginx site configuration
desc:
 - Places configured config file in /etc/nginx/sites-available.d/*.conf and links it to /etc/nginx/sites-enabled.
variables:
  site:
    name: Name of config file
  html_root:
    name: Path to public dir
  domain_name:
    name: Domain name
    desc: server_name directive
  php_fpm:
    name: PHP-FPM socket to pass requests
  type:
    name: Project type
  ssl_enable:
    name: Enable ssl?
  ssl_crt:
    name: Certificate content
  ssl_key:
    name: Certificate key content
  ssl_ciphers:
    name: Enabled ciphers
  ssl_protocols:
    name: Enabled protocols
